PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = 6

# Increase CR Version with each major release.
CR_VERSION := 13.0

# Internal version
LINEAGE_VERSION := GhostDroid-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-$(GHOST_EDITION)

# Display version
LINEAGE_DISPLAY_VERSION := GhostDroid-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-$(GHOST_EDITION)
